#pragma once
#include <furi.h>
#include <gui/gui.h>
#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/submenu.h>
#include <gui/modules/variable_item_list.h>

#include "scenes/scene.h"
#include "types.h"

/* generated by fbt from .png files in images folder */
#include <sensors_icons.h>

// keep track of app view
typedef enum {
    SensorsAppView_Menu,
    SensorsAppView_SensorConfig
} SensorsAppView;

// custom events for choosing sensor
typedef enum {
    SensorsAppEvent_UseDummySensor,
    SensorsAppEvent_UseBH1750,
} SensorsAppEvent;

// menu selections
typedef enum {
    SensorsAppMenu_SelectDummySensor,
    SensorsAppMenu_SelectBH1750,
} SensorsAppSelection;
