#pragma once
#include <furi.h>
#include <gui/gui.h>
#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/byte_input.h>
#include <gui/modules/submenu.h>
#include <gui/modules/variable_item_list.h>
#include <gui/modules/text_box.h>

#include "scenes/scene.h"
#include "util/i2c_trx.h"

/* generated by fbt from .png files in images folder */
#include <sensors_icons.h>

// app views, various UI arrangements
typedef enum {
    SensorsAppView_Menu,
    SensorsAppView_SensorConfig,
    SensorsAppView_ByteInput,
    SensorsAppView_TextBox,
} SensorsAppView;

// custom events for app states
typedef enum {
    SensorsAppEvent_UseDummySensor,
    SensorsAppEvent_UseBH1750,
    SensorsAppEvent_EnterBytes,
    SensorsAppEvent_Send
} SensorsAppEvent;

// menu selections
typedef enum {
    SensorsAppMenu_SelectDummySensor,
    SensorsAppMenu_SelectBH1750,
} SensorsAppSelection;

// keep track of app context
typedef struct {
    SceneManager* sm;
    ViewDispatcher* vd;
    I2CTRx* it;

    Submenu* main_menu;
    VariableItemList* sensor_config;
    ByteInput* byte_input;
    TextBox* text_box;

    char text_store[40];
} SensorsApp;
