#include <furi.h>
#include <gui/gui.h>
#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>

/* generated by fbt from .png files in images folder */
#include <sensors_icons.h>

typedef enum {
    SensorsAppScene_MainMenu,
    SensorsAppScene_Sensor,
    SensorsAppScene_count
} SensorsAppScene;

typedef struct {
    SceneManager* sm;
    ViewDispatcher* vd;
} SensorsApp;

int32_t sensors_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm sensors!");

    return 0;
}
